# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import uber.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=24, verbose_name='Short Name')),
                ('api_url', models.URLField(verbose_name='Uber API Url')),
                ('ssl_client_key', models.FileField(blank=True, upload_to=uber.models.get_ssl_directory)),
                ('ssl_client_cert', models.FileField(blank=True, upload_to=uber.models.get_ssl_directory)),
                ('api_version', models.CharField(blank=True, max_length=8, verbose_name='API Version')),
                ('event_name', models.CharField(blank=True, max_length=64, verbose_name='Name')),
                ('org_name', models.CharField(blank=True, max_length=64, verbose_name='Organization Name')),
                ('year', models.CharField(blank=True, max_length=4)),
                ('epoch', models.DateTimeField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=128, verbose_name='Venue Name')),
                ('venue_address', models.CharField(blank=True, max_length=128, verbose_name='Venue Address')),
                ('at_the_con', models.BooleanField()),
                ('post_con', models.BooleanField()),
            ],
        ),
    ]
