# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 01:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='epoch',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True),
        ),
    ]
