# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import uber.models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0002_auto_20161010_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('prod', 'Production'), ('dev', 'Development')], default='dev', max_length=8, verbose_name='Instance Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=24, unique=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ssl_client_cert',
            field=models.FileField(upload_to=uber.models.get_ssl_directory),
        ),
        migrations.AlterField(
            model_name='event',
            name='ssl_client_key',
            field=models.FileField(upload_to=uber.models.get_ssl_directory),
        ),
    ]
