# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0003_auto_20161011_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=24, primary_key=True, serialize=False, unique=True, verbose_name='Short Name'),
        ),
    ]
