# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementsSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=32, verbose_name=b'Department')),
                ('specific_department', models.CharField(blank=True, max_length=32, verbose_name=b'Specific Department')),
                ('first_name', models.CharField(max_length=32, verbose_name=b'First Name')),
                ('last_name', models.CharField(max_length=32, verbose_name=b'Last Name')),
                ('contact_email', models.CharField(max_length=40, verbose_name=b'Contact E-Mail')),
                ('create_av_request', models.BooleanField(default=False, verbose_name=b'Requires A/V')),
                ('need_pa', models.BooleanField(default=False, verbose_name=b'Requires PA')),
                ('need_wired_mic', models.BooleanField(default=False, verbose_name=b'Requires Wired Mic')),
                ('need_wireless_mic', models.BooleanField(default=False, verbose_name=b'Requires Wireless Mic')),
                ('need_laptop_input', models.BooleanField(default=False, verbose_name=b'Requires Laptop Input')),
                ('need_other_audio', models.BooleanField(default=False, verbose_name=b'Other Audio Requirements')),
                ('need_projector', models.BooleanField(default=False, verbose_name=b'Requires Projector')),
                ('need_projection_screen', models.BooleanField(default=False, verbose_name=b'Requires Projection Screen')),
                ('need_lcd_monitor', models.BooleanField(default=False, verbose_name=b'Requires LCD Monitor')),
                ('need_tv', models.BooleanField(default=False, verbose_name=b'Requires Television')),
                ('need_dvd_player', models.BooleanField(default=False, verbose_name=b'Requires Blu-ray/DVD Player')),
                ('need_other_video', models.BooleanField(default=False, verbose_name=b'Other Video Requirements')),
                ('av_details', models.TextField(blank=True, verbose_name=b'A/V Request Details')),
                ('need_lighting', models.BooleanField(default=False, verbose_name=b'Requires Lighting')),
                ('lighting_details', models.TextField(blank=True, verbose_name=b'Lighting Request Details')),
                ('create_network_request', models.BooleanField(default=False, verbose_name=b'Requires Network')),
                ('network_type', models.CharField(blank=True, choices=[(b'wifi', b'WiFi'), (b'wired', b'Wired (Ethernet)'), (b'both', b'Both')], max_length=24, verbose_name=b'Connection Type')),
                ('num_wired_drops', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b'Wired Drop Count')),
                ('wired_drops_location', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Wired Drop Location')),
                ('num_wireless_users', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b'Wireless User Count')),
                ('other_net_requirements', models.TextField(blank=True, verbose_name=b'Other Network Requests')),
                ('create_laptop_request', models.BooleanField(default=False, verbose_name=b'Requires Laptops')),
                ('num_laptops', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b'Laptop Count')),
                ('need_internet_access', models.BooleanField(default=False, verbose_name=b'Internet')),
                ('need_uber_access', models.BooleanField(default=False, verbose_name=b'Uber')),
                ('need_digital_signage', models.BooleanField(default=False, verbose_name=b' Digital Signage')),
                ('need_other_laptops', models.BooleanField(default=False, verbose_name=b'Other')),
                ('need_custom_software', models.BooleanField(default=False, verbose_name=b'Laptops need custom software')),
                ('other_laptop_requirements', models.TextField(blank=True, verbose_name=b'Other Laptop Requests')),
                ('create_power_request', models.BooleanField(default=False, verbose_name=b'Requires Power')),
                ('num_power_strips', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b'Power Strip Count')),
                ('num_25ft_cords', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b"25' Extension Cord Count")),
                ('num_50ft_cords', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b"50' Extension Cord Count")),
                ('other_power_requirements', models.TextField(blank=True, verbose_name=b'Other Power Requests')),
                ('create_phone_request', models.BooleanField(default=False, verbose_name=b'Requires IP Phones')),
                ('num_phones', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b'IP Phone Count')),
                ('phone_location', models.CharField(blank=True, max_length=64, verbose_name=b'Phone Deployment Location')),
                ('other_phone_requirements', models.TextField(blank=True, verbose_name=b'Other Phone Requests')),
                ('create_radio_request', models.BooleanField(default=False, verbose_name=b'Requires Radios')),
                ('num_radios', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b'Radio Count')),
                ('num_headsets', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b'Headset Count')),
                ('other_radio_requirements', models.TextField(blank=True, verbose_name=b'Other Radio Requests')),
                ('create_tape_request', models.BooleanField(default=False, verbose_name=b'Requires Tape')),
                ('num_rolls', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b'Tape Roll Count')),
                ('other_tape_requirements', models.TextField(blank=True, verbose_name=b'Other Tape Requests')),
                ('other_request', models.TextField(blank=True, verbose_name=b'Other Requests')),
                ('feedback_rating', models.CharField(blank=True, choices=[(b'very_poor', b'really sucks'), (b'poor', b'sucks'), (b'neutral', b"ain't bad"), (b'good', b'is awesome'), (b'very_good', b'is really awesome')], max_length=24, verbose_name=b'Feedback Rating')),
                ('feedback_comments', models.TextField(blank=True, verbose_name=b'Comments')),
            ],
        ),
    ]
