# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0002_auto_20161010_2113'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementssubmission',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uber.Event'),
        ),
    ]
