# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_requirementssubmission_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementssubmission',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'Request Submitted'),
            preserve_default=False,
        ),
    ]
